### ISSUE TITLE
import error: ModuleNotFoundError: No module named '_lzma'

### ISSUE THREAD

**Issue by MinXu1991** [sentinel-hub/sentinelhub-py#135]
Hi,

I successfully installed sentinelhub using python 3.6.2 on Linux. When I imported it, I got the error below:
I got the same error using python 3.7.0.

>>> import sentinelhub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/m/.local/lib/python3.6/site-packages/sentinelhub/__init__.py", line 5, in <module>
    from .data_request import WmsRequest, WcsRequest, FisRequest, GeopediaWmsRequest, GeopediaImageRequest, \
  File "/home/m/.local/lib/python3.6/site-packages/sentinelhub/data_request.py", line 13, in <module>
    from .ogc import OgcImageService
  File "/home/m/.local/lib/python3.6/site-packages/sentinelhub/ogc.py", line 15, in <module>
    from .download import DownloadRequest, get_json
  File "/home/m/.local/lib/python3.6/site-packages/sentinelhub/download/__init__.py", line 6, in <module>
    from .client import DownloadClient, get_json, get_xml
  File "/home/m/.local/lib/python3.6/site-packages/sentinelhub/download/client.py", line 14, in <module>
    from ..decoding import decode_data as decode_data_function
  File "/home/m/.local/lib/python3.6/site-packages/sentinelhub/decoding.py", line 12, in <module>
    import tifffile as tiff
  File "/home/m/.local/lib/python3.6/site-packages/tifffile/__init__.py", line 3, in <module>
    from .tifffile import __doc__, __all__, __version__, main
  File "/home/m/.local/lib/python3.6/site-packages/tifffile/tifffile.py", line 12146, in <module>
    import lzma
  File "/apps/python/3.6.2/lib/python3.6/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'

What might cause this problem?

Thanks in advance!

**Comment by batic** [comment]
See for instance [this issue](https://github.com/pandas-dev/pandas/issues/27532). You will have to have `liblzma-dev` installed on your system prior! to having a particular python version installed.

**Comment by MinXu1991** [comment]
Thanks!
