### ISSUE TITLE
[BUG] Sentinelhub installation fails on Python3.9 (MacOS)

### ISSUE THREAD

**Issue by RakibFiha** [sentinel-hub/sentinelhub-py#148]
**Description**

sentinelhub installation fails in Python3.9.0 with:

```
  ERROR: Command errored out with exit status 1:
   command: /Users/mdrakiburrahman/Environments/2.Current_Work/sentinel/bin/python3 /Users/mdrakiburrahman/Environments/2.Current_Work/sentinel/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/d1/qs0j875s6bv5sf96hq524pdr0000gn/T/tmp7t5659qc
       cwd: /private/var/folders/d1/qs0j875s6bv5sf96hq524pdr0000gn/T/pip-install-kw75_6y3/pyproj
  Complete output (34 lines):
  PROJ_DIR is set, using existing proj4 installation..

  Traceback (most recent call last):
    File "/Users/mdrakiburrahman/Environments/2.Current_Work/sentinel/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Users/mdrakiburrahman/Environments/2.Current_Work/sentinel/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/mdrakiburrahman/Environments/2.Current_Work/sentinel/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/d1/qs0j875s6bv5sf96hq524pdr0000gn/T/pip-build-env-a6scv08l/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/private/var/folders/d1/qs0j875s6bv5sf96hq524pdr0000gn/T/pip-build-env-a6scv08l/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/d1/qs0j875s6bv5sf96hq524pdr0000gn/T/pip-build-env-a6scv08l/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/d1/qs0j875s6bv5sf96hq524pdr0000gn/T/pip-build-env-a6scv08l/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 243, in <module>
      ext_modules=get_extension_modules(),
    File "setup.py", line 147, in get_extension_modules
      proj_dir = get_proj_dir()
    File "setup.py", line 60, in get_proj_dir
      check_proj_version(proj_dir)
    File "setup.py", line 20, in check_proj_version
      proj_ver_bytes = subprocess.check_output(proj, stderr=subprocess.STDOUT)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 501, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: '/Users/mdrakiburrahman/Environments/2.Current_Work/sentinel/bin/proj'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/mdrakiburrahman/Environments/2.Current_Work/sentinel/bin/python3 /Users/mdrakiburrahman/Environments/2.Current_Work/sentinel/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/d1/qs0j875s6bv5sf96hq524pdr0000gn/T/tmp7t5659qc Check the logs for full command output.
```

**To Reproduce**

Create a venv: `python3 -m venv ./`
Activate: `. ./bin/activate`

1. Install `sentinelsat` with pip: `pip3 install sentinelsat`
2. Install `geos_c` with if missing by: `brew install geos` 
3. sentinelhub with pip: `pip install sentinelhub --upgrade` 

**Expected behavior**

It should successfully install sentinelhub without any error.

**Environment**

Python version
```
$ python3 -V
Python 3.9.0
```

requirements.txt looks like following:
```
$ pip3 freeze
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
geojson==2.5.0
geomet==0.2.1.post1
html2text==2020.1.16
idna==2.10
requests==2.24.0
sentinelsat==0.14
six==1.15.0
tqdm==4.51.0
urllib3==1.25.11
```

**Desktop:**

 - OS: MacOS Catalina 10.15.4 Beta
```
$ uname -a
Darwin MacBookPro-4.local 19.4.0 Darwin Kernel Version 19.4.0: Sun Feb  9 22:12:38 PST 2020; root:xnu-6153.100.196~21/RELEASE_X86_64 x86_64
```

**Comment by AleksMat** [comment]
Hi @RakibFiha,

It seems that you have a problem installing `pyproj` package which is a dependency package of `sentinelhub`. If you run `pip install pyproj` you should get the same error.

I suspect that you are missing a system library `proj`. Maybe it can be installed with `brew`? Otherwise I suggest checking [`pyproj` installation guide](https://pyproj4.github.io/pyproj/latest/installation.html) or openning an issue at their GitHub repo.

**Comment by RakibFiha** [comment]
Thank you, I have opened an issue at pyproj. Seems like, I will have to install PROJ, setup PROJ_DIR and compile it as mentioned here: https://github.com/pyproj4/pyproj/issues/729#issuecomment-718731257

**Comment by RakibFiha** [comment]
```brew install proj``` solved the problem.
