### ISSUE TITLE
[BUG] sentinelhub.aws error when trying to download product

### ISSUE THREAD

**Issue by JanWev** [sentinel-hub/sentinelhub-py#184]
when using sentinel-hub.aws command line tool I get I strange error message which seems to be related to a CRS request. I actually don't even understand, why it should be used. The error message is shown below.

E:\S2_scene_collection>sentinelhub.aws --product S2B_MSIL1C_20200826T105619_N0209_R094_T30TXQ_20200826T121824

Traceback (most recent call last):
  File "e:\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "e:\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda3\Scripts\sentinelhub.aws.exe\__main__.py", line 5, in <module>
  File "e:\anaconda3\lib\site-packages\sentinelhub\__init__.py", line 5, in <module>
    from .data_request import WmsRequest, WcsRequest, FisRequest, GeopediaWmsRequest, GeopediaImageRequest, \
  File "e:\anaconda3\lib\site-packages\sentinelhub\data_request.py", line 13, in <module>
    from .ogc import OgcImageService
  File "e:\anaconda3\lib\site-packages\sentinelhub\ogc.py", line 11, in <module>
    from .constants import ServiceType, MimeType, CRS, SHConstants, CustomUrlParam
  File "e:\anaconda3\lib\site-packages\sentinelhub\constants.py", line 56, in <module>
    class CRSMeta(EnumMeta):
  File "e:\anaconda3\lib\site-packages\sentinelhub\constants.py", line 59, in CRSMeta
    _UNSUPPORTED_CRS = pyproj.CRS(4326)
  File "e:\anaconda3\lib\site-packages\pyproj\crs\crs.py", line 296, in __init__
    super().__init__(projstring)
  File "pyproj/_crs.pyx", line 2338, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: epsg:4326: (Internal Proj Error: proj_create: cannot build geodeticCRS 4326: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of
_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date)

I get the same error when trying to download a tile using the following command:
E:\S2_scene_collection>sentinelhub.aws --tile T30TXQ 2020-08-26

**Desktop (please complete the following information):**

 - OS: Windows
 - Browser: Chrome (not used for execution)
 -

**Comment by AleksMat** [comment]
Hi @JanWev,

It seems that your insallation of `pyproj` dependency package is not working correctly. If you are using pip to install packages on Windows I recommend installing `pyproj` from [Windows wheels repository](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyproj). The same applies for `shapely` package.

**Comment by JanWev** [comment]
Ok, thanks @AleksMat. Somehow the pip install did not raise any issue, but said "installed successfully". I will try to install the packages  using wheel and come back to you later.

**Comment by AleksMat** [comment]
Closing an old issue.
