### ISSUE TITLE
[BUG] Unable to download Sentinel images earlier than 2018

### ISSUE THREAD

**Issue by thanastasiadis** [sentinel-hub/sentinelhub-py#220]
**Describe the bug**

Unable to download Sentinel images from aws S3 that are earlier than 2018 as the productInfo.json url is invalid on roda.sentinel-hub.com

**To Reproduce**

1. Setup the aws credentials
2. Run `sentinelhub.aws --product S2A_MSIL1C_20151125T095332_N0204_R079_T33TXL_20151125T095500`
3. Check the error message on the terminal output

**Expected behavior**

A product with name: S2A_MSIL1C_20151125T095332_N0204_R079_T33TXL_20151125T095500.SAFE should have been downloaded on the current working directory.

**Environment**

Python 3.6.9
Dependencies:
```
aenum==3.1.0
asn1crypto==0.24.0
boto3==1.18.62
botocore==1.21.62
certifi==2021.10.8
chardet==4.0.0
click==7.1.2
cryptography==2.1.4
dataclasses==0.8
dataclasses-json==0.5.6
GDAL==2.2.2
geojson==2.5.0
geomet==0.3.0
html2text==2020.1.16
idna==2.6
jmespath==0.10.0
keyring==10.6.0
keyrings.alt==3.0
marshmallow==3.14.0
marshmallow-enum==1.5.1
mypy-extensions==0.4.3
numpy==1.19.5
oauthlib==3.1.1
Pillow==8.4.0
psycopg2==2.8.6
pycrypto==2.6.1
PyGObject==3.26.1
pyproj==3.0.1
python-apt==1.6.5+ubuntu0.7
python-dateutil==2.8.2
pyxdg==0.25
requests==2.25.1
requests-oauthlib==1.3.0
s3transfer==0.5.0
SecretStorage==2.3.1
sentinelhub==3.4.0
sentinelsat==0.13
Shapely==1.7.0
six==1.11.0
tifffile==2020.9.3
tqdm==4.62.3
typing-extensions==3.10.0.2
typing-inspect==0.7.1
unattended-upgrades==0.1
urllib3==1.26.7
utm==0.7.0
```

**Stack trace or screenshots**

```
root@b745121c67a8:/eo-tools/downloader/sentinelhub-downloader# sentinelhub.aws --product S2A_MSIL1C_20151125T095332_N0204_R079_T33TXL_20151125T095500
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/download/handlers.py", line 22, in new_download_func
    return download_func(self, request)
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/download/client.py", line 152, in _execute_download
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://roda.sentinel-hub.com/sentinel-s2-l1c/products/2015/11/25/S2A_MSIL1C_20151125T095332_N0204_R079_T33TXL_20151125T095500/productInfo.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sentinelhub.aws", line 8, in <module>
    sys.exit(aws())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/commands.py", line 67, in aws
    download_safe_format(product_id=product, folder=folder, redownload=redownload, bands=band_list)
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/data_request.py", line 945, in download_safe_format
    AwsProductRequest(product_id, data_folder=folder, bands=bands, safe_format=True)
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/data_request.py", line 802, in __init__
    super().__init__(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/data_request.py", line 758, in __init__
    super().__init__(AwsDownloadClient, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/data_request.py", line 47, in __init__
    self.create_request()
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/data_request.py", line 807, in create_request
    metafiles=self.metafiles, config=self.config)
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/aws.py", line 338, in __init__
    self.product_info = client.get_json(self.get_url(AwsConstants.PRODUCT_INFO))
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/download/client.py", line 209, in get_json
    return self._single_download(request, decode_data=True)
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/download/client.py", line 119, in _single_download
    response_content = self._execute_download(request)
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/download/handlers.py", line 72, in new_download_func
    return download_func(self, request)
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/download/aws_client.py", line 29, in _execute_download
    return super()._execute_download(request)
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/download/handlers.py", line 44, in new_download_func
    return download_func(self, request)
  File "/usr/local/lib/python3.6/dist-packages/sentinelhub/download/handlers.py", line 27, in new_download_func
    raise DownloadFailedException(_create_download_failed_message(exception, request.url)) from exception
sentinelhub.exceptions.DownloadFailedException: Failed to download from:
https://roda.sentinel-hub.com/sentinel-s2-l1c/products/2015/11/25/S2A_MSIL1C_20151125T095332_N0204_R079_T33TXL_20151125T095500/productInfo.json
with HTTPError:
404 Client Error: Not Found for url: https://roda.sentinel-hub.com/sentinel-s2-l1c/products/2015/11/25/S2A_MSIL1C_20151125T095332_N0204_R079_T33TXL_20151125T095500/productInfo.json
Server response: ""
```

**Desktop (please complete the following information):**

 - OS: Linux b745121c67a8 4.14.246-187.474.amzn2.x86_64 #1 SMP Tue Sep 7 21:48:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
The same happens for all these products :

- S2A_MSIL2A_20160327T100012_N0201_R122_T33TWL_20160327T100012
- S2A_MSIL2A_20160426T100032_N0213_R122_T33TWL_20210121T125921
- S2A_MSIL2A_20170227T095021_N0204_R079_T33TWL_20170227T095613
- S2B_MSIL2A_20170804T100029_N0213_R122_T33TWL_20210107T074849

**Comment by AleksMat** [comment]
Hi @thanastasiadis,

I checked and it seems that these products are not in the AWS archive. Therefore they cannot be downloaded with `sentinelhub-py` package.

However, it seems that they are available at [Creodias](https://finder.creodias.eu/).

**Comment by thanastasiadis** [comment]
@AleksMat

The aws bucket has these products.

https://registry.opendata.aws/sentinel-2/ 
According to the link above: "L2A data are available from September 2016 over wider Europe", so considering the "T33TWL" is in Croatia (Europe), the following should have been available:

- S2A_MSIL2A_20170227T095021_N0204_R079_T33TWL_20170227T095613
- S2B_MSIL2A_20170804T100029_N0213_R122_T33TWL_20210107T074849

I also found these data on the S3 bucket:

```
[ec2-user@...]$ aws s3 ls s3://sentinel-s2-l2a/products/2017/2/27/S2A_MSIL1C_20170227T095021_N0204_R079_T33UXQ_20170227T095613.SAFE/ --request-payer requester 
                           PRE datastrip/
2021-04-09 12:36:55      72725 L2AManifest.xml
2021-04-09 12:36:55      18626 inspire.xml
2021-04-09 12:36:55      60003 manifest.safe
2021-04-09 12:36:55      53324 metadata.xml
2021-04-09 12:36:55       1055 productInfo.json
2021-04-09 12:36:55     198706 report.xml
```

I guess the root cause is that the "roda" sever doesn't have the .json meta files for these products, and probably for any product earlier than 2018.

**Comment by AleksMat** [comment]
Roda just offers a public access to some metadata files on an S3 bucket. You can see that for the product, for which you found the content on the bucket, the same content can be found through Roda:

https://roda.sentinel-hub.com/sentinel-s2-l2a/products/2017/2/27/S2A_MSIL1C_20170227T095021_N0204_R079_T33UXQ_20170227T095613.SAFE/productInfo.json

**Comment by thanastasiadis** [comment]
I have checked that the roda server
S2A_MSIL1C_20151125T095332_N0204_R079_T33TXL_20151125T095500

**Comment by thanastasiadis** [comment]
Any ideas on how to proceed with this issue? 
Currently, Sentinel hub doesn't download images that are earlier than 2018.

**Comment by gmilcinski** [comment]
Just to add to this conversation, that AWS S3 registry contains global L2A data going back to 1.1.2017. More or less each S2 L1C product was processed to L2A level (with some exceptions due to cloudiness).  

In the inital report you are referring to Sentinel-2 L1C product, which is actually not available on AWS. This might have happened for various reasons. There are other products from same date available though:  
https://roda.sentinel-hub.com/sentinel-s2-l1c/products/2015/11/25/

With all that said, sentinelhub-py is an open-source library so pull requests are more than welcome. Our company's focus is providing access via Sentinel Hub API, so this issue specifically is not high on our priority.

**Comment by AleksMat** [comment]
Closing this issue as there is nothing we can do in `sentinelhub-py` package code about a few missing Sentinel-2 products in AWS archives.
