### ISSUE TITLE
[BUG] exception when calling get_data method

### ISSUE THREAD

**Issue by sanjivjha** [sentinel-hub/sentinelhub-py#225]
**Describe the bug**
```python
request = AwsTileRequest(
        tile=tile_name,
        time=time,
        aws_index=aws_index,
        bands=bands,
        metafiles=metafiles,
        data_folder=data_folder,
        #data_collection=DataCollection.SENTINEL2_L1C
        data_collection=DataCollection.SENTINEL2_L2A
    ) 
data_list = request.get_data(save_data=saveFile,max_threads = 20)
```

This code was working perfectly but the lastest update is  causing the exception
```
Traceback (most recent call last):
  File "/opt/ml/processing/code/sentinel2_data_processing_ver4.py", line 506, in <module>
    main()
  File "/opt/ml/processing/code/sentinel2_data_processing_ver4.py", line 502, in main
    initiateSentinel2DataProcessing(dc)
  File "/opt/ml/processing/code/sentinel2_data_processing_ver4.py", line 496, in initiateSentinel2DataProcessing
    csv_output_file = processSentinel2Data(download_config)
  File "/opt/ml/processing/code/sentinel2_data_processing_ver4.py", line 456, in processSentinel2Data
    shapeFile,initTimeStamp,endTimeStamp,bands,False)
  File "/opt/ml/processing/code/sentinel2_data_processing_ver4.py", line 372, in processTilesDataForGivenTimeRange
    data_list,file10,file20 = getData(tiles[i],bands,download_dir,saveFile)
  File "/opt/ml/processing/code/sentinel2_data_processing_ver4.py", line 91, in getData
    data_list = request.get_data(save_data=saveFile,max_threads = 20)  # This will not redownload anything because data is already stored on disk
  File "/usr/local/lib/python3.7/dist-packages/sentinelhub/data_request.py", line 120, in get_data
    decode_data=decode_data)
  File "/usr/local/lib/python3.7/dist-packages/sentinelhub/data_request.py", line 179, in _execute_data_download
    data_list = client.download(filtered_download_list, max_threads=max_threads, decode_data=decode_data)
  File "/usr/local/lib/python3.7/dist-packages/sentinelhub/download/client.py", line 87, in download
    data_list[future_order[future]] = self._process_download_future(future)
  File "/usr/local/lib/python3.7/dist-packages/sentinelhub/download/client.py", line 97, in _process_download_future
    return future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sentinelhub/download/client.py", line 116, in _single_download
    self._check_cached_request_is_matching(request, request_path)
  File "/usr/local/lib/python3.7/dist-packages/sentinelhub/download/client.py", line 168, in _check_cached_request_is_matching
    cached_request_info = read_data(request_path, MimeType.JSON)
  File "/usr/local/lib/python3.7/dist-packages/sentinelhub/io_utils.py", line 41, in read_data
    if not os.path.exists(filename):
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by AleksMat** [comment]
Hi @sanjivjha, could you provide all information so that we'll be able to reproduce the error?

Please provide the values that you are using for variables `tile_name, time, aws_index, bands, metafiles, data_folder`.

**Comment by AleksMat** [comment]
Closing issue for now as no additional info was provided. Feel free to reopen and provide sufficient information to reproduce the issue.
