### ISSUE TITLE
Error when `pip install sentinelhub`

### ISSUE THREAD

**Issue by PeterFogh** [sentinel-hub/sentinelhub-py#26]
Hi, I'm installing your model using pip in a Conda environment, like I did about a month ago where it worked.
However, today it failed with this error. 
```
λ pip install sentinelhub --upgrade
Collecting sentinelhub
  Using cached sentinelhub-1.1.1.tar.gz
Requirement already up-to-date: click in c:\users\user\appdata\local\continuum\anaconda3\envs\data_science\lib\site-packages (from sentinelhub)
Collecting cython (from sentinelhub)
  Using cached Cython-0.28.1-cp36-cp36m-win_amd64.whl
Collecting matplotlib (from sentinelhub)
  Using cached matplotlib-2.2.2-cp36-cp36m-win_amd64.whl
Collecting numpy (from sentinelhub)
  Using cached numpy-1.14.2-cp36-none-win_amd64.whl
Collecting opencv-python (from sentinelhub)
  Using cached opencv_python-3.4.0.12-cp36-cp36m-win_amd64.whl
Collecting pip==9.0.1 (from sentinelhub)
  Using cached pip-9.0.1-py2.py3-none-any.whl
Collecting pyproj (from sentinelhub)
  Using cached pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    nad2bin.c
    nad2bin.c(129): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    nad2bin.c(130): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    nad2bin.c(137): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    nad2bin.c(138): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    nad2bin.c(352): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    nad2bin.c(353): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
    pj_malloc.c
    Generating code
    Finished generating code
    LINK : fatal error LNK1158: cannot run 'rc.exe'
    using bundled proj4..
    Traceback (most recent call last):
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\data_science\lib\distutils\_msvccompiler.py", line 519, in link
        self.spawn([self.linker] + ld_args)
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\data_science\lib\distutils\_msvccompiler.py", line 542, in spawn
        return super().spawn(cmd)
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\data_science\lib\distutils\ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\data_science\lib\distutils\spawn.py", line 38, in spawn
        _spawn_nt(cmd, search_path, dry_run=dry_run)
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\data_science\lib\distutils\spawn.py", line 81, in _spawn_nt
        "command %r failed with exit status %d" % (cmd, rc))
    distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-build-opj49wbm\pyproj\setup.py", line 74, in <module>
        cc.link_executable(objects, execname, extra_postargs = [ '/MANIFEST' ] if os.name == 'nt' else  None)
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\data_science\lib\distutils\ccompiler.py", line 734, in link_executable
        debug, extra_preargs, extra_postargs, None, target_lang)
      File "C:\Users\user\AppData\Local\Continuum\anaconda3\envs\data_science\lib\distutils\_msvccompiler.py", line 522, in link
        raise LinkError(msg)
    distutils.errors.LinkError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-build-opj49wbm\pyproj\
```

I asked Google about the error and found this fix, https://stackoverflow.com/a/44563421/7796217, which lets me install the model without any errors. However, this requires that I'm running the installation in a terminal with administrator permissions, else I get the following error:
```
Exception:
Traceback (most recent call last):
  File "c:\users\user\appdata\local\continuum\anaconda3\envs\data_science\lib\shutil.py", line 387, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\user\\AppData\\Local\\Temp\\pip-ba9_depc-uninstall\\users\\user\\appdata\\local\\continuum\\anaconda3\\envs\\data_science\\lib\\site-packages\\matplotlib\\backends\\_backend_agg.cp36-win_amd64.pyd
'```

I hope you can find a solution such that the installation only requires to run `pip install sentinelhub --upgrade`.

**Comment by AleksMat** [comment]
Thanks for letting us know about the error and the solution.

It seems that installing dependency packages that require C/C++ complier (e.g. `tifffile`, `pyproj`) is causing quite a few problems for Windows users. On Linux or iOS we haven't had any such problems yet.

In the future we will try to find a more general solution to avoid them. Maybe by adding pre-compiled binaries of dependency packages into to the package release. However I am not sure if that is the best solution...

**Comment by PeterFogh** [comment]
You are welcome.

**Comment by PeterFogh** [comment]
Thanks, @j08lue.  :) 
Just for later readers, you have to add conda-forge as a channel, before you can install `tifffile`, this i done by `conda config --add channels conda-forge`.

**Comment by MattKovtun** [comment]
Thx guys! Did everything what you mentioned, while installing got an error 
`"python setup.py egg_info"  failed with error code 1 in ... \pip-install-9v_704tv\shapely\`
Just installed shapely and everything was ok.

**Comment by PeterFogh** [comment]
@AleksMat I'm fine with closing this issue, as the installation of the sentinelhub-py Conda package works as it should.
Wil you close this issue?

**Comment by AleksMat** [comment]
Thanks for reminding us. Here is the link to conda-forge release of sentinelhub-py for future references: 

https://anaconda.org/conda-forge/sentinelhub

Closing the issue.
