### ISSUE TITLE
sentinel chain.

### ISSUE THREAD

**Issue by ampp2** [sentinel-hub/sentinelhub-py#28]
(base) R:\Forest2020\ampp2\pyeo>Python sen2chain.py
Traceback (most recent call last):
  File "sen2chain.py", line 28, in <module>
    main()
  File "sen2chain.py", line 23, in main
    save_query_output(products)
  File "R:\Forest2020\ampp2\pyeo\Sen2Search.py", line 79, in save_query_output
    pickle.dump(products, output_file)
TypeError: write() argument must be str, not bytes

**Comment by AleksMat** [comment]
Hello ampp2,

your error message does not mention `sentinelhub` package at all. Could you describe what code are you trying to run and what does it have to do with this package?
