### ISSUE TITLE
Problem with Downloading as .SAFE with Product ID Older than Jan 2016

### ISSUE THREAD

**Issue by sscullen** [sentinel-hub/sentinelhub-py#30]
I updated to the ver 2.0, trying to download an older product with multiple granules per product into .SAFE format, I get a FILE NOT FOUND ERROR for the first band .jp2 on the first granule. The .SAFE structure is created, and all the granule folders show up, but there is no actual data or metadata found. Regular download not using .SAFE format parameter works fine.

I was using a relative path name for the `download_folder` parameter in `AwsProductRequest` function, so I tried an absolute path. This did not work either. The product id was `S2A_OPER_PRD_MSIL1C_PDMC_20160407T043302_R107_V20160405T085012_20160405T085012` 

Here's the full traceback:

Traceback (most recent call last):
  File "D:\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "D:\Winter2018\Sentinel2-DDPython\sentinel2dd.py", line 535, in download_task
    job_status['download_status'] = download_product(product['title'], download_folder_path, product['platformname'])
  File "D:\Winter2018\Sentinel2-DDPython\sentinel2dd.py", line 358, in download_product
    download_result = product_request.save_data()
  File "D:\Winter2018\Sentinel2-DDPython\venv\lib\site-packages\sentinelhub\data_request.py", line 100, in save_data
    self._execute_data_download(redownload, max_threads, raise_all_errors=False)
  File "D:\Winter2018\Sentinel2-DDPython\venv\lib\site-packages\sentinelhub\data_request.py", line 119, in _execute_data_download
    data_list.append(future.result(timeout=SHConfig().download_timeout_seconds))
  File "D:\Python36\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "D:\Python36\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "D:\Python36\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\Winter2018\Sentinel2-DDPython\venv\lib\site-packages\sentinelhub\download.py", line 236, in execute_download_request
    _save_if_needed(request, response_content)
  File "D:\Winter2018\Sentinel2-DDPython\venv\lib\site-packages\sentinelhub\download.py", line 333, in _save_if_needed
    with open(request.file_location, 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Winter2018\\Sentinel2-DDPython\\temp\\S2A_OPER_PRD_MSIL1C_PDMC_20160407T043302_R107_V20160405T085012_201604
05T085012.SAFE\\GRANULE\\S2A_OPER_MSI_L1C_TL_SGS__20160405T124601_A004108_T35TQK_N02.01\\IMG_DATA\\S2A_OPER_MSI_L1C_TL_SGS__20160405T124601_A004108_T35TQK_B01.jp2'

Not sure what I am doing wrong here. Thanks!

**Comment by mkadunc** [comment]
Some software has been known to have problems with the length of the path in the .SAFE format. Have you tried storing output to e.g. D:\ ?

**Comment by sscullen** [comment]
Thanks very much, I will do a test with linux and windows 10 myself (I suspect you are right tho, I am using an older system with windows 7). Is there any remedy for this, or is the solution to run your script on a non-windows platform? My main concern with any shortening of the file names would be how sen2cor would handle products with different names. If it is possible for sen2cor to correct individual granules, could an option be added to create the individual granules as individual modern .SAFE COMPACT products, which could be then be corrected by sen2cor? 

Any advice on which way to proceed? Thanks again!
