### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aashishd** [sentinel-hub/sentinelhub-py#320]
**Describe the bug**
I found this bug while working on `eo-grow` framework, but the bug needs to fixed in the `sentinelhub` library.

While using the pipeline `eogrow.pipelines.BatchDownload`, we use the `BatchAreaManager` with that. When we run a new pipeline a batch_request is created and submitted to SH Batch API. Then the pipeline internally, tries to call the `AreaManager.cache_grid()` function, which calls the `sentinelhub.BatchSplitter` which further calls SentinelHubBatch.get_tiling_grid(grid_id) which first fetches the url using internal method _get_tiling_grids_url(grid_id) to get the grid url and then fetches the json object containing the grid information.
So, in case the grid_id is `0`, the logic in `_get_tiling_grids_url(grid_id)` in the line 4 of the function, where grid_id is treated as None and it returns an incorrect url (which fetch information about all grids).

```
    def _get_tiling_grids_url(self, grid_id: Union[None, str, int] = None) -> str:
        """Creates a URL for tiling grids endpoint"""
        url = f"{self.service_url}/tilinggrids"
        # because grid_id can also be 0
        if grid_id:
            return f"{url}/{grid_id}"
        return url
```

**This last call fails, the grid caching functions, as it tries to look for height & width properties in the returned json when the properties are not in there. It can be seen in the end of the stack trace.**

**To Reproduce**

Run the  `eogrow.pipelines.BatchDownload`, for any region with area config as following : 
```
"area": {
    "manager": "eogrow.core.area.BatchAreaManager",
    "area_filename": "any_file.geojson",
    "resolution": "60",
    "tiling_grid_id": "0"
  }
```

**Expected behavior**

It should ideally, save the cached grid details after running the `eogrow.pipelines.BatchDownload` and not give an error.

**Environment**

```
eo-grow==1.2.0
eo-learn==1.2.0
psycopg2-binary==2.9.3
pydantic==1.9.1
geopandas==0.11.0
sentinelhub>=3.6.3
seaborn==0.11.2
fs>=2.2.0
lightgbm>=3.3.2
rasterio==1.2.10
scikit-learn==1.1.1
scipy==1.8.1
pytest
```

**Stack trace or screenshots**

```
	(uc_land-cover) ubuntu@ip-172-29-236-120:/home/ashish/uc_land-cover/landcover-py$ eogrow config_files/load_batch.json
	INFO eogrow.core.pipeline:237: Running BatchDownloadPipeline
	INFO eogrow.core.area.base:155: Calculating a unary union of the geometries
	INFO eogrow.core.area.base:169: Finished processing area geometry
	INFO eogrow.core.area.base:183: Saving area geometry to cache/area_mini-aoi_BatchAreaManager__.gpkg
	INFO eogrow.pipelines.download_batch:166: Created a new batch request with ID 1441b403-a1da-42a6-ae23-1d98a2306bed
	INFO eogrow.pipelines.download_batch:237: Started running batch job.
	INFO eogrow.pipelines.download_batch:138: Waiting to finish analyzing job with ID 1441b403-a1da-42a6-ae23-1d98a2306bed
	INFO sentinelhub.api.batch:744: Batch job has a status CREATED, sleeping for 10 seconds
	INFO sentinelhub.api.batch:744: Batch job has a status CREATED, sleeping for 10 seconds
	INFO eogrow.core.area.base:174: Loading cached area geometry from cache/area_mini-aoi_BatchAreaManager__.gpkg
	Traceback (most recent call last):
	  File "/home/ashish/envs/uc_land-cover/bin/eogrow", line 8, in <module>
	    sys.exit(EOGrowCli.main())
	  File "/home/ashish/envs/uc_land-cover/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
	    return self.main(*args, **kwargs)
	  File "/home/ashish/envs/uc_land-cover/lib/python3.8/site-packages/click/core.py", line 1055, in main
	    rv = self.invoke(ctx)
	  File "/home/ashish/envs/uc_land-cover/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
	    return ctx.invoke(self.callback, **ctx.params)
	  File "/home/ashish/envs/uc_land-cover/lib/python3.8/site-packages/click/core.py", line 760, in invoke
	    return __callback(*args, **kwargs)
	  File "/home/ashish/envs/uc_land-cover/lib/python3.8/site-packages/eogrow/cli.py", line 95, in main
	    pipeline.run()
	  File "/home/ashish/envs/uc_land-cover/lib/python3.8/site-packages/eogrow/core/pipeline.py", line 240, in run
	    finished, failed = self.run_procedure()
	  File "/home/ashish/envs/uc_land-cover/lib/python3.8/site-packages/eogrow/pipelines/download_batch.py", line 145, in run_procedure
	    self.ensure_batch_grid(batch_request.request_id)
	  File "/home/ashish/envs/uc_land-cover/lib/python3.8/site-packages/eogrow/pipelines/download_batch.py", line 259, in ensure_batch_grid
	    self.area_manager.cache_grid()
	  File "/home/ashish/envs/uc_land-cover/lib/python3.8/site-packages/eogrow/core/area/base.py", line 124, in cache_grid
	    self._create_and_save_grid(grid_filename, ignore_region_filter)
	  File "/home/ashish/envs/uc_land-cover/lib/python3.8/site-packages/eogrow/core/area/base.py", line 199, in _create_and_save_grid
	    grid = self._create_new_split(area_geometry)
	  File "/home/ashish/envs/uc_land-cover/lib/python3.8/site-packages/eogrow/core/area/batch.py", line 89, in _create_new_split
	    splitter = BatchSplitter(batch_request=batch_request, config=self.storage.sh_config)
	  File "/home/ashish/envs/uc_land-cover/lib/python3.8/site-packages/sentinelhub/areas.py", line 645, in __init__
	    self.tile_size = self._get_tile_size()
	  File "/home/ashish/envs/uc_land-cover/lib/python3.8/site-packages/sentinelhub/areas.py", line 656, in _get_tile_size
	    return grid_info["properties"]["tileWidth"], grid_info["properties"]["tileHeight"]
KeyError: 'properties'
```

**Desktop (please complete the following information):**

 - OS: Ubuntu 18.04

**Additional context**

**Comment by zigaLuksic** [comment]
Yes, that is a bug and it occurs in many of the functions there. Thanks for finding it.

**Comment by zigaLuksic** [comment]
Will be fixed in next release.

**Comment by aashishd** [comment]
Thank you so much for the fix @zigaLuksic
