### ISSUE TITLE
Access denied on Sentinel-2 l1c

### ISSUE THREAD

**Issue by prinsherbert** [sentinel-hub/sentinelhub-py#57]
Whenever I run

    # sentinelhub.aws --tile T33XWJ 2018-04-02

I get an access denied for `sentinel-s2-l1c` `tiles/33/X/WJ/2018/4/2/4/qi/GEOMETRIC_QUALITY.xml`:

I configured as described here:

https://sentinelhub-py.readthedocs.io/en/latest/configure.html#amazon-s3-capabilities

But did not add any permission policies in the AWS IAM console (should I?)

```
Traceback (most recent call last):
  File "/home/herbert/.virtualenvs/eye/bin/sentinelhub.aws", line 10, in <module>
    sys.exit(aws())
  File "/home/herbert/.virtualenvs/eye/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/herbert/.virtualenvs/eye/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/herbert/.virtualenvs/eye/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/herbert/.virtualenvs/eye/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/herbert/.virtualenvs/eye/lib/python3.6/site-packages/sentinelhub/commands.py", line 65, in aws
    bands=band_list, data_source=data_source)
  File "/home/herbert/.virtualenvs/eye/lib/python3.6/site-packages/sentinelhub/data_request.py", line 932, in download_safe_format
    safe_request.save_data(redownload=redownload)
  File "/home/herbert/.virtualenvs/eye/lib/python3.6/site-packages/sentinelhub/data_request.py", line 130, in save_data
    self._execute_data_download(data_filter, redownload, max_threads, raise_download_errors)
  File "/home/herbert/.virtualenvs/eye/lib/python3.6/site-packages/sentinelhub/data_request.py", line 165, in _execute_data_download
    data_list.append(future.result(timeout=SHConfig().download_timeout_seconds))
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/herbert/.virtualenvs/eye/lib/python3.6/site-packages/sentinelhub/download.py", line 239, in execute_download_request
    response = _do_aws_request(request)
  File "/home/herbert/.virtualenvs/eye/lib/python3.6/site-packages/sentinelhub/download.py", line 313, in _do_aws_request
    return s3_client.get_object(Bucket=bucket_name, Key=url_key, RequestPayer='requester')
  File "/home/herbert/.virtualenvs/eye/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/herbert/.virtualenvs/eye/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied
```

**Comment by AleksMat** [comment]
Hi @prinsherbert,

Thanks for pointing this out - besides [configuration instructions](https://sentinelhub-py.readthedocs.io/en/latest/configure.html#amazon-s3-capabilities) you also have to set a permission policy to your AWS user in AWS IAM console.

One of possible permissions for this use case is _AmazonS3ReadOnlyAccess_ but you can of course choose any other permission which would allow reading from s3 buckets.

We will add a sentence about this into configuration instructions for future reference.
