### ISSUE TITLE
Stuck downloading at 15%

### ISSUE THREAD

**Issue by hazemati** [sentinel-hub/sentinelhub-py#80]
I've tried running a script to download satellite info, and it keeps getting stuck downloading. The first time it was stuck at 30%, the second time at 15% (I let it run for over an hour). You'll find the error log below. 
Querying products: 100%|██████████| 12456/12456 [02:12<00:00, 103.29 products/s]
Downloading:   1%|▏                          | 4.19M/806M [00:30<41:48, 320kB/s]^C
Traceback (most recent call last):
  File "VVermSentinal.py", line 38, in <module>
    senintal.download_all_pictures("16 marshall street newton ma 02459")
  File "VVermSentinal.py", line 26, in download_all_pictures
    self.api.download_all(products)
  File "/usr/local/lib/python3.6/dist-packages/sentinelsat/sentinel.py", line 602, in download_all
    product_info = self.download(product_id, directory_path, checksum)
  File "/usr/local/lib/python3.6/dist-packages/sentinelsat/sentinel.py", line 542, in download
    product_info['url'], temp_path, self.session, product_info['size'])
  File "/usr/local/lib/python3.6/dist-packages/sentinelsat/sentinel.py", line 826, in _download
    for chunk in r.iter_content(chunk_size=chunk_size):
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/houman/.local/lib/python3.6/site-packages/urllib3/response.py", line 465, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/houman/.local/lib/python3.6/site-packages/urllib3/response.py", line 413, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/usr/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
KeyboardInterrupt

**Comment by batic** [comment]
Sorry, but that error has nothing to do with sentinelhub-py library. The error is from sentinelsat package.
